apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster-001
  region: ap-southeast-1
  version: "1.29"

managedNodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 10
    iam:
      withAddonPolicies:
        autoScaler: true

addons:
  - name: aws-ebs-csi-driver
    version: latest

iam:
  withOIDC: true
